name: coachwhip
favicon: null
layout_spectrum: 0.97515
typography_spectrum: 0.73604
title: Coachwhip Publications
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010006'
    - '#ffffff'
    - '#403f43'
    - '#c50026'
    - '#e07f93'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
